package com.example.designsystem.theme

import androidx.compose.ui.graphics.Color

/**
 * Material Design 3 color tokens for the Travio app theme.
 *
 * This file contains color definitions for:
 * - Light theme (standard, medium contrast, high contrast)
 * - Dark theme (standard, medium contrast, high contrast)
 *
 * Contrast levels follow WCAG accessibility guidelines:
 * - Standard: Default contrast
 * - Medium: Enhanced contrast for better readability
 * - High: Maximum contrast (WCAG AAA compliant)
 */

// ============================================
// Light Theme - Standard Contrast
// ============================================
val primaryLight = Color(0xFF00535B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF006D77)
val onPrimaryContainerLight = Color(0xFF9BECF7)
val secondaryLight = Color(0xFF236863)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF83C5BE)
val onSecondaryContainerLight = Color(0xFF00534E)
val tertiaryLight = Color(0xFF394856)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF50606E)
val onTertiaryContainerLight = Color(0xFFC9DAEB)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF7FAFA)
val onBackgroundLight = Color(0xFF181C1D)
val surfaceLight = Color(0xFFFBF9F8)
val onSurfaceLight = Color(0xFF1B1C1B)
val surfaceVariantLight = Color(0xFFDFE3E1)
val onSurfaceVariantLight = Color(0xFF434846)
val outlineLight = Color(0xFF737877)
val outlineVariantLight = Color(0xFFC3C7C5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303030)
val inverseOnSurfaceLight = Color(0xFFF3F0EF)
val inversePrimaryLight = Color(0xFF82D3DE)
val surfaceDimLight = Color(0xFFDCD9D9)
val surfaceBrightLight = Color(0xFFFBF9F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F2)
val surfaceContainerLight = Color(0xFFF0EDEC)
val surfaceContainerHighLight = Color(0xFFEAE8E7)
val surfaceContainerHighestLight = Color(0xFFE4E2E1)

// ============================================
// Light Theme - Medium Contrast (Enhanced Accessibility)
// ============================================
val primaryLightMediumContrast = Color(0xFF003D43)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF006D77)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF003E3A)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF347872)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF283845)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF50606E)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF7FAFA)
val onBackgroundLightMediumContrast = Color(0xFF181C1D)
val surfaceLightMediumContrast = Color(0xFFFBF9F8)
val onSurfaceLightMediumContrast = Color(0xFF111111)
val surfaceVariantLightMediumContrast = Color(0xFFDFE3E1)
val onSurfaceVariantLightMediumContrast = Color(0xFF323736)
val outlineLightMediumContrast = Color(0xFF4E5352)
val outlineVariantLightMediumContrast = Color(0xFF696E6D)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF303030)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF3F0EF)
val inversePrimaryLightMediumContrast = Color(0xFF82D3DE)
val surfaceDimLightMediumContrast = Color(0xFFC8C6C5)
val surfaceBrightLightMediumContrast = Color(0xFFFBF9F8)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF6F3F2)
val surfaceContainerLightMediumContrast = Color(0xFFEAE8E7)
val surfaceContainerHighLightMediumContrast = Color(0xFFDFDCDB)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD3D1D0)

// ============================================
// Light Theme - High Contrast (WCAG AAA Compliant)
// ============================================
val primaryLightHighContrast = Color(0xFF003237)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF005159)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF00322F)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF00534E)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF1E2E3A)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF3B4B58)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF7FAFA)
val onBackgroundLightHighContrast = Color(0xFF181C1D)
val surfaceLightHighContrast = Color(0xFFFBF9F8)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDFE3E1)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF282D2C)
val outlineVariantLightHighContrast = Color(0xFF454A49)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF303030)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF82D3DE)
val surfaceDimLightHighContrast = Color(0xFFBAB8B8)
val surfaceBrightLightHighContrast = Color(0xFFFBF9F8)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF3F0EF)
val surfaceContainerLightHighContrast = Color(0xFFE4E2E1)
val surfaceContainerHighLightHighContrast = Color(0xFFD6D4D3)
val surfaceContainerHighestLightHighContrast = Color(0xFFC8C6C5)

// ============================================
// Dark Theme - Standard Contrast
// ============================================
val primaryDark = Color(0xFF82D3DE)
val onPrimaryDark = Color(0xFF00363C)
val primaryContainerDark = Color(0xFF006D77)
val onPrimaryContainerDark = Color(0xFF9BECF7)
val secondaryDark = Color(0xFF9EE1DA)
val onSecondaryDark = Color(0xFF003734)
val secondaryContainerDark = Color(0xFF83C5BE)
val onSecondaryContainerDark = Color(0xFF00534E)
val tertiaryDark = Color(0xFFB8C8D9)
val onTertiaryDark = Color(0xFF22323F)
val tertiaryContainerDark = Color(0xFF50606E)
val onTertiaryContainerDark = Color(0xFFC9DAEB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101415)
val onBackgroundDark = Color(0xFFE0E3E3)
val surfaceDark = Color(0xFF131313)
val onSurfaceDark = Color(0xFFE4E2E1)
val surfaceVariantDark = Color(0xFF434846)
val onSurfaceVariantDark = Color(0xFFC3C7C5)
val outlineDark = Color(0xFF8D9290)
val outlineVariantDark = Color(0xFF434846)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E2E1)
val inverseOnSurfaceDark = Color(0xFF303030)
val inversePrimaryDark = Color(0xFF006972)
val surfaceDimDark = Color(0xFF131313)
val surfaceBrightDark = Color(0xFF393939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1B1C1B)
val surfaceContainerDark = Color(0xFF1F201F)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFF353534)

// ============================================
// Dark Theme - Medium Contrast (Enhanced Accessibility)
// ============================================
val primaryDarkMediumContrast = Color(0xFF98E9F4)
val onPrimaryDarkMediumContrast = Color(0xFF002A2F)
val primaryContainerDarkMediumContrast = Color(0xFF4A9CA7)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFA6E9E1)
val onSecondaryDarkMediumContrast = Color(0xFF002B28)
val secondaryContainerDarkMediumContrast = Color(0xFF83C5BE)
val onSecondaryContainerDarkMediumContrast = Color(0xFF00332F)
val tertiaryDarkMediumContrast = Color(0xFFCDDEEF)
val onTertiaryDarkMediumContrast = Color(0xFF172734)
val tertiaryContainerDarkMediumContrast = Color(0xFF8293A2)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF101415)
val onBackgroundDarkMediumContrast = Color(0xFFE0E3E3)
val surfaceDarkMediumContrast = Color(0xFF131313)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF434846)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD9DDDB)
val outlineDarkMediumContrast = Color(0xFFAEB3B1)
val outlineVariantDarkMediumContrast = Color(0xFF8C9190)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE4E2E1)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2A2A)
val inversePrimaryDarkMediumContrast = Color(0xFF005058)
val surfaceDimDarkMediumContrast = Color(0xFF131313)
val surfaceBrightDarkMediumContrast = Color(0xFF454444)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF070707)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1E1D)
val surfaceContainerDarkMediumContrast = Color(0xFF282828)
val surfaceContainerHighDarkMediumContrast = Color(0xFF333232)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3E3E3D)

// ============================================
// Dark Theme - High Contrast (WCAG AAA Compliant)
// ============================================
val primaryDarkHighContrast = Color(0xFFCAF8FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF7ECFDA)
val onPrimaryContainerDarkHighContrast = Color(0xFF000E10)
val secondaryDarkHighContrast = Color(0xFFB9FDF5)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF8CCFC8)
val onSecondaryContainerDarkHighContrast = Color(0xFF000E0C)
val tertiaryDarkHighContrast = Color(0xFFE5F1FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFB4C5D5)
val onTertiaryContainerDarkHighContrast = Color(0xFF000D17)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF101415)
val onBackgroundDarkHighContrast = Color(0xFFE0E3E3)
val surfaceDarkHighContrast = Color(0xFF131313)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF434846)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFECF1EF)
val outlineVariantDarkHighContrast = Color(0xFFBFC4C2)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE4E2E1)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF005058)
val surfaceDimDarkHighContrast = Color(0xFF131313)
val surfaceBrightDarkHighContrast = Color(0xFF50504F)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1F201F)
val surfaceContainerDarkHighContrast = Color(0xFF303030)
val surfaceContainerHighDarkHighContrast = Color(0xFF3B3B3B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF474746)
