name: Pull Request Checks

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: gradle

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: Build
        run: ./gradlew assembleDebug

      - name: Build Tester Device Artifact
        run: ./gradlew :app:assembleTesterDeviceRelease

      - name: Validate Release Endpoints
        run: ./gradlew :app:validateCanonicalReleaseEndpoints

